# Generated by Django 5.0.2 on 2024-03-23 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppHeladeria', '0002_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
                ('dni', models.CharField(max_length=35)),
            ],
        ),
    ]
